### PR TITLE
Radial distribution function

### PR DESCRIPTION
**Pull request by danijoo**
An implementation to calculate the radial distribution function.

### CODE REVIEW

**Comment by padix-key** [comment]
If you do not have any objections, I'd be happy to merge the PR.

**Comment by danijoo** [comment]
I think it's fine as it is. 


---- On Wed, 13 Feb 2019 17:25:05 +0100 notifications@github.com wrote ----



If you do not have any objections, I'd be happy to merge the PR.

**Comment by padix-key** [comment]
I had to remove the `scipy.signal` part from the doctest lines in the `rdf()` docstring, as `scipy` must not be required to execute the doctests.

**Comment by padix-key** [comment]
It's now merged. Thank you.

**Pull request merged**
