### PR TITLE
fix gro id overflow - fixes #96

### LINKED ISSUE #96: GRO writer atom_id overflow
When gro files with more then 100.000 atoms are written, the atom id field becomes to large, resulting in files that cannot be read by biotite anymore and also not displayed by PyMOL.

*Steps to reproduce:*
Create a file with more then 100.000 atoms. For examle:
```bash
gmx editconf -f spc216.gro -o huge_box.gro -box 20 20 20
gmx solvate -cp huge_box.gro -cs spc216.gro -o huge_box.gro
head huge_box.gro
> 216H2O,WATJP01,SPC216,SPC-MODEL,300K,BOX(M)=1.86206NM,WFVG,MAR. 1984
> 786570
>     1SOL     OW    1  10.221  10.629  10.122
>     1SOL    HW1    2  10.128  10.627  10.159
>     1SOL    HW2    3  10.222  10.590  10.030
```

Now if we read in this box and write it out again, we cant read it in a second time because of a file format violation at line 100002 of thefile:
```python
import biotite.structure.io as io
s = io.load_structure("huge_box.gro")
print(len(s)) # 786570
io.save_structure("huge_box2.gro", s)
s = io.load_structure("huge_box2.gro")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bauer/conda/lib/python3.7/site-packages/biotite/structure/io/general.py", line 78, in load_structure
    array = file.get_structure()
  File "/home/bauer/conda/lib/python3.7/site-packages/biotite/structure/io/gro/file.py", line 190, in get_structure
    array.coord[m,i,0] = float(line[20:28])*10
ValueError: could not convert string to float: '0   3.70'
```

*huge_box2.gro*
```bash
33332SOL    HW299996   2.494   7.113  15.071
33333SOL     OW99997   3.512   7.306  16.291
33333SOL    HW199998   3.565   7.316  16.207
33333SOL    HW299999   3.485   7.396  16.325
33334SOL     OW100000   3.703   5.761  15.860
33334SOL    HW1100001   3.742   5.676  15.824
33334SOL    HW2100002   3.605   5.763  15.841
33335SOL     OW100003   2.125   5.912  15.616
33335SOL    HW1100004   2.046   5.963  15.582
```

The correct behaviour would be to start writing atom ids with 1 after atom #99.999.

### PR DESCRIPTION
**Pull request by danijoo**
This is a fix for #96 . I basically copy-pasted the solution you used for overflowing pdb files and wrote an appropriate unit test.

Cheers

### CODE REVIEW

**Comment by padix-key** [comment]
I think you mean issue #96. I updated the number in the title and in the description.

**Comment by danijoo** [comment]
Indeed!

**Comment by padix-key** [comment]
Somehow, the AppVeyor  build does not find `numpy`. I'll have a look into it.

**Comment by padix-key** [comment]
Otherwise, your PR looks great. I will merge it, as soon as I found out what is the issue with AppVeyor.

**Comment by padix-key** [comment]
After all, I introduced a small change: The .gro file format supports residue IDs up to 99999 (5 characters).

**Comment by padix-key** [comment]
The issue seems independent of ypur PR. Therefore, I will merge it regardless.

**Pull request merged**
