### PR TITLE
Improve filters for nucleotides, amino acids and add filter for carbohydrates.

### PR DESCRIPTION
**Pull request by tomtomhdx**
This PR implements part of the changes discussed in #424:

- `filter_amino_acids()` now uses an extended amino acid list extracted from the _PDB Chemical Component Dictionary_, where the `_chem_comp.type` property corresponds to peptide monomers.
- The nucleotide list for `filter_nucleotides()` was updated using the current version of the _PDB Chemical Component Dictionary_.
- `filter_carbohydrates()` filters for residues, where the `_chem_comp.type` corresponds to polysaccharide monomers.
- `filter_canonical_amino_acids()` filters for the 22 proteinogenic amino acids.
- `filter_canonical_nucleotides()` filters for the canonical DNA/RNA nucleotides A, C, G, T/U.
- Analogous to `nucleotide_names()`, `carbohydrate_names()` and `amino_acid_names()` return a list of all monomers that correspond to polysachharide and peptide monomers respectively.

I am unsure why `filter_amino_acids()` checks that the `res_id` is not -1:
`return ( np.isin(array.res_name, _amino_acid_list) & (array.res_id != -1) )`

### CODE REVIEW

**Review by padix-key — APPROVED** [review]
Thank you for the implementation, the changes look good to me.

As final remark I would suggest writing a second sentence in the `filter_xxx()` docstrings that mentions the origin from the CCD and the included `_chem_comp.type`.

**Comment by tomtomhdx** [comment]
> Thank you for the implementation, the changes look good to me.
> 
> As final remark I would suggest writing a second sentence in the `filter_xxx()` docstrings that mentions the origin from the CCD and the included `_chem_comp.type`.

Good Idea! I added the `_chem_comp.type` values to the respective _Notes_ section of the functions.

**Comment by padix-key** [comment]
Thanks. Can i merge this PR?

**Comment by tomtomhdx** [comment]
Yes its ready from my side.

**Comment by padix-key** [comment]
> I am unsure why filter_amino_acids() checks that the res_id is not -1:
return ( np.isin(array.res_name, _amino_acid_list) & (array.res_id != -1) )

It seems like I overlooked this part of your comment. I think I added this condition, since `res_id` is often `-1` in mmCIF files, if a residue is not part of a chain. As this is not true for all file formats and sometimes amino acids inside a chain also get such residue ID, I would propose removing this extra condition.

**Comment by tomtomhdx** [comment]
I completely forgot about that! I will remove the extra condition then.

**Pull request merged**
