### PR TITLE
Cleaned up superimpose code

### PR DESCRIPTION
**Pull request by claudejrogers**
Removed duplicate code handling different cases with AtomArray versus AtomArrayStack input.
Fixed random bug in geometry.py that would have affected error handling.

### CODE REVIEW

**Review by padix-key — APPROVED** [review]
Thank you, the changes look good to me. Now that the function is based on coordinates, we could also think about allowing also directly coordinate `ndarray`s as parameter for `superimpose()` and `superimpose_apply()` as alternative to `AtomArray`/`AtomArrayStack`. Do you have an opinion on this and would you like to implement it in this PR or is this feature something for the future?

**Comment by claudejrogers** [comment]
Yes, that is a good idea. I can do that in a later PR.

**Review by padix-key — CHANGES_REQUESTED** [review]
Hi, I found an edge case where the code change does not work: If an input structure with only a single model or atom is given, these dimensions are also 'squeezed'. I added a test case and a fix in this review.

**Comment by claudejrogers** [comment]
Good catch on the single-model AtomArrayStack.

I would think the minimum number of atoms in the inputs, or after applying a mask, should be 3. 
With 2 input atoms, the covariance matrix would have shape 2 x 2.

**Comment by padix-key** [comment]
The covariance matrix should include 3x3 entries independent of the number of atoms to my understanding, since it gives the covariance for the coordinate components, i.e.
```
Cov(X,X), Cov(X,Y), Cov(X,Z)
Cov(Y,X), Cov(Y,Y), Cov(Y,Z)
Cov(Z,X), Cov(Z,Y), Cov(Z,Z)
```

**Comment by padix-key** [comment]
I merge the PR then, thank you for the effort!

**Comment by claudejrogers** [comment]
I'm referring to this line in `_superimpose`

```python
    # Calculate covariance matrix
    cov = np.dot(x.T, y)
```

If x and y are 2 x 3, `cov` will be 2 x 2.

Plus, "superimposing" to one or two atoms is underspecified, since there are infinite equally valid solutions.

**Comment by padix-key** [comment]
I tested this line of code and it always returns a `3x3` matrix for me independent of the number of atoms, as `x` is transposed.
Apart from that I agree with you that superimposing one or two atoms onto another set of atoms does not give an unambiguous solution. Maybe a warning could be given in this scenario.

**Pull request merged**
