### PR TITLE
Use sphinxcontrib-bibtex for citation management

### PR DESCRIPTION
**Pull request by padix-key**
This PR introduces the usage of `sphinxcontrib-bibtex` for citation management in the entire project. Although this adds a new dependency for building the documentation and requires contributors to use a *BibTeX* file, this change has some significant advantages:

- Reduction of potentially malformed citations
- Enforced consistent citation style
- Easy way to globally change the citation style
- Adding a DOI to each of the existing citations

### CODE REVIEW

**Comment by padix-key** [comment]
@tomtomhdx @danijoo If I remember correctly, you already used citations in dcostrings. Do you have an opinion about adding citation information to a BibTeX file compared to manual citations in a docstring?

**Comment by danijoo** [comment]
I like bibtex because they can be more easily exported and are consistent across the repo.

**Comment by tomtomhdx** [comment]
I agree with @danijoo.

Also I would imagine it is more comfortable to enter citations in the BibTeX format than having to manually match the right citation format in the docstring.

**Comment by padix-key** [comment]
Thank you for your feedback. In this case I will merge this PR.

**Pull request merged**
