### PR TITLE
plot_sequence_logo now uses a profile

### PR DESCRIPTION
**Pull request by MaxGreil**
I rewrote biotite.sequence.graphics.plot_sequence_logo() that it now accepts a profile as input parameter.

@padix-key can you have a look?

### CODE REVIEW

**Comment by padix-key** [comment]
The code changes look good to me, thank you. Could you also update the existing examples in the gallery to the new API (`doc/examples/scripts/sequence/lexa_conservation.html` and `doc/examples/scripts/sequence/anderson_logo.html`)?

**Comment by MaxGreil** [comment]
@padix-key I added the requested changes

**Comment by padix-key** [comment]
Thanks. The example gallery is not built in the CI workflows, so I will build the examples before I merge this PR, to check whether the changes work as expected.

**Comment by padix-key** [comment]
The examples work as expected :+1:.

**Pull request merged**
