### PR TITLE
Add `filter_polymer()`

### PR DESCRIPTION
**Pull request by edikedik**
Implementing `filter_polymer()` discussed [here](https://github.com/biotite-dev/biotite/issues/424).

This function enables quick filtering for consecutive atoms that are a part of standard macromolecular polymers of the desired minimum size.

(There are commits from [another pull request](https://github.com/biotite-dev/biotite/pull/430). I'm unsure whether Github will recognize them as redundant after merging it.)

### CODE REVIEW

**Comment by padix-key** [comment]
Thanks for implementing this. Am I assuming right, that I can close PR #430 in favor of this one?

**Comment by edikedik** [comment]
> Thanks for implementing this. Am I assuming right, that I can close PR #430 in favor of this one?

Correct, it's just one commit more compared to #430.

**Review by padix-key — CHANGES_REQUESTED** [review]
Here are some minor changes, I would like to request before I merge this PR.

**Comment by padix-key** [comment]
I just added a commit that replaces the now deprecated functions in other places of the code base and I added the new functions to the proper categories in the API reference.

**Review by padix-key — CHANGES_REQUESTED** [review]
Minor fix in the review

**Comment by padix-key** [comment]
I just saw that you are not yet listed in the `CONTRIB.rst`. You may add yourself there, if you like.

**Review by padix-key — APPROVED** [review]
Thanks for implementing the changes. Can I merge this PR?

**Comment by edikedik** [comment]
> Thanks for implementing the changes. Can I merge this PR?

Happy to contribute.
Yes.

**Pull request merged**
